## Basic Configuration

baseurl = "https://nishantuniyal.github.io"
builddrafts = false
canonifyurls = false
languageCode = "en-US"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"

author = "Nishant Uniyal"
title = "Nishant Uniyal"

theme = "hugo-goa"

## Hugo Built-in Features
disqusShortname = "personal-website-1" # Comment out to disable Disqus.
googleAnalytics = "UA-44582128-1"
enableRobotsTXT = true

## Site Settings
[params]
author = "Nishant Uniyal"
intro = "Data Scientist"
description = "Now @Boeing Vancouver. Previously @Clarius Mobile Health"
authorimage = "headshot.jpg"
dateformat = "Jan 2, 2006"

## Site Meta Settings
[params.meta]
description = "Nishant Uniyal"
keywords = "nishant,nishantuniyal,blog,website,datascience"

## Social Accounts
[params.social]
github = "nishantuniyal"
# instagram = "<username>"
# xing = "<username>"
linkedin = "nishantuniyal"
twitter = "nishant_nu"
# facebook = "<username>"
# google = "nishantuniyal"
# stackoverflow = "<username>"
email = "nishantuniyal@gmail.com"

## Extras
[params.extra]
copyright = "© 2016. Nishant Uniyal. [Some Rights Reserved](http://creativecommons.org/licenses/by/3.0/)."
poweredby = false
highlightjs = true

## Main Menu
[[menu.main]]
    name = "blog"
    identifier = "blog"
    weight = 100
    url = "/blog/"
[[menu.main]]
    name = "about"
    identifier = "about"
    weight = 200
    url = "/about/"
